### ISSUE TITLE
[Enhancement] Hardcode texts localizable

### ISSUE THREAD

**Issue by Lyaiya** [Ridanisaurus/EmendatusEnigmatica#100]
**Mod Version**
1.16.5-1.2.8

**Describe the bug/enhancement**
Wood Dust's tooltip is hardcode.

In JEI info, some ore spawn informations are hardcode.

**Expected behavior**
Add language key for these hardcode texts.

**Screenshots**
![1](https://user-images.githubusercontent.com/9733114/127676787-f65bf69f-6dc1-4715-901e-8f2e0029ac2e.png)

![2](https://user-images.githubusercontent.com/9733114/127676792-5c7a2481-88de-491a-8261-986cad7df804.png)

![3](https://user-images.githubusercontent.com/9733114/127676761-811ca4cd-0270-47f9-a826-ca39ce2d8299.png)

**Comment by Ridanisaurus** [comment]
All hardcoded texts will be changed to Keys in EE V2.0
