### ISSUE TITLE
[Bug] Remove Nether Quartz and Gold Ores from the Basalt Deltas in the Nether.

### ISSUE THREAD

**Issue by Ridanisaurus** [Ridanisaurus/EmendatusEnigmatica#104]
https://github.com/NillerMedDild/Enigmatica6/issues/2918

**Comment by The-Arcanian** [comment]
Its not just Basalt Deltas. I just came to report finding Nether Quartz in the Netherrack round a Ruined Portal, despite Nether Quartz generation being disabled in the Overworld.

**Comment by Ridanisaurus** [comment]
Yea, ore generation in incorrect dims if the block is available is fixed in the next big version as I completely re-wrote the ore generation system.
