### ISSUE TITLE
Followup - What graphics cards are supported?

### ISSUE THREAD

**Issue by mtjohnson47** [Ridanisaurus/EmendatusEnigmatica#105]
Followup to https://github.com/Ridanisaurus/EmendatusEnigmatica/issues/73.  Github won't allow me to add another comment on that issue.

What graphics cards are supported?

**Comment by Ridanisaurus** [comment]
Google Search, or ask Mojang. This is not a question for me, and it is not a bug from my mod so I'm closing this item as it's not even a report to start with.
