### ISSUE TITLE
[Enhancement] Silent Mekanism's and M&A support

### ISSUE THREAD

**Issue by furtabs** [Ridanisaurus/EmendatusEnigmatica#107]
**Mod Version**
1.2.9

**Describe the bug/enhancement**
Adding support for Silent Mekanism's Machines and their ores like Bismuth and possibly Mana and Artifice support and their vitineum

**To Reproduce - if applicable**

**Expected behavior**

**Screenshots**

**Additional context**

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Ridanisaurus** [comment]
The mod is going data-driven in a future release which will allow modpack devs to add support for any and all ores and materials. Until then, I'm avoiding the addition of manual materials as much as I can.

**Comment by Ridanisaurus** [comment]
Forgot to mention, you can look into this to help with the processing.
https://www.curseforge.com/minecraft/customization/avsps-easy-emendatus-enigmatica-scripts
