### ISSUE TITLE
EE's Silicon cannot replace RS's Silicon

### ISSUE THREAD

**Issue by ilhamfu** [Ridanisaurus/EmendatusEnigmatica#109]
**Mod Version**
EmendatusEnigmatica-1.16.5-1.2.9
refinedstorage-1.9.15

**Describe the bug/enhancement**
It seems EE silicon recipes overlap with the RS Silicon but can't replace it in the RS recipe

**Comment by Ridanisaurus** [comment]
Are you playing a specific modpack, or are you making your own?

**Comment by ilhamfu** [comment]
making my own, my current solution is disabling the recipe with craft tweaker but I hope EE can fix this issue

**Comment by Ridanisaurus** [comment]
At a quick glance, this is due to RS not using Tags for the Silicon input, and therefore the only 2 options are:
- Replace the recipes that require silicon to accept anything with `forge:silicon`
- Disable EE recipe for Silicon 

The above can be easily achieved with KubeJS/Craft Tweaker

I will review it further later on tonight, and see if I can do something from my side, but I doubt it. Will update this item with my finding.

**Comment by Ridanisaurus** [comment]
I guess in theory I can add `refinedstorage:silicon` tag to EE Silicon, but that goes against the concept of unification with tags. I'll reach out to RS Devs, and see whether they would be willing to switch to `forge:silicon` instead, especially that it is already reading for a tag. 
Example: https://github.com/refinedmods/refinedstorage/blob/mc1.16/src/main/resources/data/refinedstorage/recipes/raw_basic_processor.json

**Comment by ilhamfu** [comment]
thanks for looking up this issue, I was just about to reach out to RS Devs and AE2 Devs about this, cus both of them add silicon and didn't use a unifying tag which causes lots of unnecessary issues. maybe adding config to disable silicon can resolve this issue on the EE side

**Comment by Ridanisaurus** [comment]
This will be fixed in a future release when I release EE V2.0 which will be completely data driven registries, so modpack devs can add and remove any item they want. Until then, I would recommend either of the 2 solutions above.

**Comment by ilhamfu** [comment]
Got it, thanks for the clarification btw
