### ISSUE TITLE
Overlay textures of ores getting rendered as water with shaders

### ISSUE THREAD

**Issue by ALainxD** [Ridanisaurus/EmendatusEnigmatica#110]
So when playing with shaders just the overlay textures with the ores are getting rendered as water/reflective 

In this screenshot look at the torch reflection in the ore itself, the stone in the ''background'' has no reflection

![2021-09-10_21 26 39](https://user-images.githubusercontent.com/69924381/132906919-c8982695-5693-40a6-90f0-323d064f5de0.png)

And when playing with the best shader ( SEUS PTGI HRR Test2.1 ) the game is litteraly unplayable you can't see what ore it is.

![2021-09-10_21 30 02](https://user-images.githubusercontent.com/69924381/132907460-83558b23-9778-4043-b4f8-cf9aee90f073.png)

Maybe there is an issue with the material ID that the overlay texture represents as a water type? (i have no clue about actuall modding)

**Comment by ALainxD** [comment]
And yes i know shaders have a bad Modpack support, especially SEUS PTGI. I can offer you to help testing with shaders if you want to. Just hit me up on discord Alain#5230

**Comment by ALainxD** [comment]
![2021-09-10_22 14 42](https://user-images.githubusercontent.com/69924381/132912425-d7791946-7a06-4eef-b81b-db2892e84321.png)
also the transparency allowes you to see through the world.
I can see a Mineshaft on the bottom right that is underneath me.

**Comment by Ridanisaurus** [comment]
Are you by chance using `Graphics: Fabulous`?

**Comment by ALainxD** [comment]
So i'm still trying to figure it out/ get a work around.
I think most shaders themself are the problem because of not rendering overlays or 2d texture correctly and having issue with Forge Multilayer? 
I mean for sure the combination with shaders are the problem, the only question is does every shadermaker need to implement/optimze that for this scenario or is there maybe a good/quick solution on the mod side to fix the issue.

**Comment by ALainxD** [comment]
No i was using Graphics: Fancy

**Comment by ALainxD** [comment]
All Graphic presets did not change this at all

**Comment by Ridanisaurus** [comment]
Sadly, this is not something I can fix on my side, at least not without compromising the quality of my ores. I know for a fact that this is not an issue for a lot of Shaders, so I would either recommend you try another Shader, or reach out to the Shader's dev, and let them know that Translucent blocks are not rendering correctly in Forge Multilayer models.
Out of curiosity, are Ice blocks rendering correctly, or are they also having this X-Ray issue?

**Comment by ALainxD** [comment]
![2021-09-11_00 32 44_2](https://user-images.githubusercontent.com/69924381/132924384-5df31dfe-668f-4770-a9e0-04a57eb8fa0d.png)
From left to right packed ice / Blue Ice / Ice (normal ice)
Yes Ice is also broken but it does not wave like water(what the ore does) it's more like a glassblock where you can see behind.

**Comment by Ridanisaurus** [comment]
Then as I suspected, it's not Forge Multilayer, it's everything that is Translucent it seems.
I will go ahead and close this item as it's not something I can fix. I would recommend reaching out to the Shader's Dev for a solution. Good luck, and thanks for the thorough testing and screenshots 👍🏻

**Comment by ALainxD** [comment]
Fyi i couldn't replicate it to see through walls with ice in vanilla minecraft with the shader + optifine + forge.
Would be nice if there is some sort of placeholder mod that just places the a non Translucent overlay but just a PNG of a Minecraft:stone + ore but still matches Server modlists.

**Comment by ALainxD** [comment]
but i understand that it's a lot of work to make a ore block for each Ore+Stone type, that's why you probably use the overlay ''shortcut''

**Comment by ALainxD** [comment]
Fyi i couldn't replicate it to see through walls with ice in vanilla minecraft with the shader + optifine + forge.
I guess the Ice is intended to look like that(glassy with reflection), there is no techincal issue with it at all.

just when i add your mod and place a Ore next to ice, the reflection of the ice gets buggy.

(right side ice left side Andesite gold ore)
![Animation](https://user-images.githubusercontent.com/69924381/132928823-ec2b5452-3fc7-478e-8254-af2b2ba75d22.gif)


Would be nice if there is some sort of placeholder mod that just places a non Translucent overlay but just a PNG of a Minecraft:stone + ore but still matches Server modlists.
