### ISSUE TITLE
[Enhancement] Fortunizer mending support

### ISSUE THREAD

**Issue by tlitookilakin** [Ridanisaurus/EmendatusEnigmatica#123]
**Mod Version**
1.16.5-1.2.12

**Describe the bug/enhancement**
While it makes sense to not have the fortunizer produce usable xp, it would still be nice if mending was simulated- that is, if the operating tool had mending, some amount of durability would be repaired whenever a chunk was processed.

**Expected behavior**
When mining in person, mending more or less prevents damage to the tool because all fortunable ores also drop xp. It would be nice if this also applied to the fortunizer to remove the need for a player to mine ores manually to maintain tool durability. (IE allow for full automation of mending tools with fortunizer)

**Comment by Ridanisaurus** [comment]
The Fortunizer machine is going away in V2
