### ISSUE TITLE
Fortune Question?

### ISSUE THREAD

**Issue by HeavyDeception** [Ridanisaurus/EmendatusEnigmatica#127]
Will you be adding fortune support for the ores? Because as of 1.17 iron, gold and, copper are affected by it now? so will there be an option for it in the 1.16.5 version of the mod?

**Comment by Ridanisaurus** [comment]
In 1.16.5 version, no. That will break progression beyond description in any modpack. 
Fortunable ores however will be available for the 1.18 version of the mod (skipping 1.17, naturally)
