### ISSUE TITLE
[Enhancement] Mystical Agriculture

### ISSUE THREAD

**Issue by BamsyTheSergal** [Ridanisaurus/EmendatusEnigmatica#128]
**Mod Version**
1.16.5

**Describe the bug/enhancement**
Mystical Agriculture patch/support, It would make worlds with this extra mod installed way nicer to look at, refer to the image below.
Because at the current moment only, the Mystical Agriculture ores only spawn as stone or specific types of stone for the nether ore.

**Screenshots**
![javaw_WEx6hKUqkk](https://user-images.githubusercontent.com/12705993/144440879-1d60051e-0290-4aa7-ae0d-a2da6a389a88.png)

**Comment by Ridanisaurus** [comment]
I'm currently in the process of refactoring the whole mode, and releasing a completely data-driven version where modpack devs can add any ore they want, without the need for me to hardcode it. Once the new version is released, you should be able to create Mystical Agriculture ores with EE easily.
