### ISSUE TITLE
[Enhancement] Platinum

### ISSUE THREAD

**Issue by Janvdv** [Ridanisaurus/EmendatusEnigmatica#130]
**Mod Version**
1.16

**Describe the bug/enhancement**
Would it be possible to add Platinum as a new ore?

**Comment by Ridanisaurus** [comment]
Currently in the process of re-writing the whole mod, and part of it will allow modpack devs to add any ores they want. Until then, I won't be adding any hardcoded materials.
For more information, check the Projects -> EE V2.0
