### ISSUE TITLE
[Suggestion] Allow specify The End ores to only spawn on outer island or main island

### ISSUE THREAD

**Issue by Quarris** [Ridanisaurus/EmendatusEnigmatica#133]
**Mod Version**
EmendatusEnigmatica-1.2.15-build.7+mc1.16.5

**Describe the bug/enhancement**
As the title suggests. Add a config option per end-generated ore type whether to generate on main island, outer islands, or both.

**Comment by Ridanisaurus** [comment]
You can whitelist/blacklist biomes as needed in the config.
This system is also in the new version, and has been improved quite a bit.

**Comment by Quarris** [comment]
Yeah but there is no difference in biomes between the 2 afaik.
