### ISSUE TITLE
Data pack failed to load server 1.16.5

### ISSUE THREAD

**Issue by Enterprise12nx01** [Ridanisaurus/EmendatusEnigmatica#137]
**Mod Version**
EmendatusEnigmatica-1.2.15-build.7+mc1.16.5.jar

**Describe the bug/enhancement**
Running this on a forge server with the kubejs avsp script configured, the server throws a "failed to load data pack error" the sponge forge team has referred me here(this happens without sponge forge too)

https://github.com/DaedalusGame/Immersive-Cowardice/issues/6

**To Reproduce - if applicable**
Install on forge server
Add kubejs script
Data pack error

**Expected behavior**
The server to start without issue

**Screenshots**

**Additional context**

**Logs**
https://zerobin.net/?60e46c547dbad9f2#F7e1CtLHBOmsfvF8rz7omHIKVTm090GM0kpG6O2NsLs=

**Comment by Enterprise12nx01** [comment]
This also seems to cause singleplayer issues, or even the server somehow starts once in awhile, in both instances not soon after exploring, all mobs and chunk loading, etc freezes.  Your still able to move around, but that's about it.
Quitting the world gets stuck on "saving"
This does not happen without the kubejs script

**Comment by Ridanisaurus** [comment]
This item is irrelevant with the release of EEV2 as it was a complete re-write.
