### ISSUE TITLE
Removed mod and reinstalled... All Ores Are Gone, how do i get ores back

### ISSUE THREAD

**Issue by playboiiT** [Ridanisaurus/EmendatusEnigmatica#140]
I removed the mod bc it conflicted with applied energetics in a recipe for silicon and once reinstalled all the ores were gone including the base ores and all the ores for other mods aswell.... this is my main world and would hate to restart

**Comment by Ridanisaurus** [comment]
If a world reset is not an option, you would need to to explore new chunks for Ores. I don't have any Retrogen features at the moment, but a version of it is planned for the new version which won't be on 1.16.
