### ISSUE TITLE
textures is not loading

### ISSUE THREAD

**Issue by joooom** [Ridanisaurus/EmendatusEnigmatica#175]
### Issue description

I used the demo setting for testing and textures the textures just don't load. https://i.imgur.com/go87WEq.png

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.0

### Emendatus Enigmatica version

2.0.x (Latest)

**Comment by Ridanisaurus** [comment]
The Demo Configs on Github are used for my testing purposes. Textures should be provided through a Resource Pack. 
If you have already provided the textures through a resource pack, then could you please upload your work on Github so I can investigate it.

**Comment by FooterMan14** [comment]
When a material has the ore property, you have to give it oreDrop. But also:
`{
  "id": "aluminum",
  "source": "modded",
  "localizedName": "Aluminum",
  "processedTypes": [
    "ore",
    "storage_block",
    "ingot",
    "nugget",
    "raw",
    "dust",
    "plate",
    "gear",
    "rod",
    "sword",
    "pickaxe",
    "axe",
    "shovel",
    "hoe",
    "paxel",
    "helmet",
    "chestplate",
    "leggings",
    "boots",
    "shield",
    "cluster",
    "fluid",
    "slurry",
    "crystal",
    "shard",
    "clump",
    "dirty_dust",
    "gas",
    "crushed_ore"
  ],
  "properties": {
    "materialType": "metal",
    "harvestLevel": 2,
    "isBurnable": true,
    "burnTime": 1600,
    "isEmissive": true,
    "hasOxidization": true
  ,
  "colors": {
    "fluidColor": "c5dbed",
    "materialColor": "c5dbed",
    "gasColor":"98b350",
    "oxidizationColor": "781c22"
  },
  "gas": {
    "isBurnable": true,
    "burnTime": 40,
    "energyDensity": 200,
    "isRadioactive": true,
    "radioactivity": 0.5,
    "isCoolant": true,
    "coolantType": "heated",
    "thermalEnthalpy": 0.4,
    "conductivity": 0.7
  },
  "compat": {
    "create": true,
    "occultism": false,
    "mekanism": true
  }
}`
This is from the Gitbook site. You're missing a curly brace at line 43.
