### ISSUE TITLE
Invalid character appears

### ISSUE THREAD

**Issue by blackwhita** [Ridanisaurus/EmendatusEnigmatica#180]
### Issue description

Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: EmendatusEnigmatica:sounds.json

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.0

### Emendatus Enigmatica version

2.0.x (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://paste.ubuntu.com/p/cq5phSKkcY/

**Comment by Ridanisaurus** [comment]
I have no idea who or what mod is adding EmendatusEnigmatica:sounds.json as this is not natively added by Emendatus Enigmatica itself.
If this file is added by you in a Resource Pack or something along these lines, make sure you have the mod name in lowercase.
