### ISSUE TITLE
Create-compat Crushed Ores do not recieve textures from resource packs

### ISSUE THREAD

**Issue by EnbyChu** [Ridanisaurus/EmendatusEnigmatica#181]
### Issue description

When using a custom resource pack to change the textures of added metal ore and material blocks, the textures for every type of item load without issue, _except_ for the Crushed Ores for compatibility with the Create mod. The textures I am using are straight from the Resources on the EEV2 Wiki, and thus are all named properly. I'm not sure if this is actually an issue on EEV2's end or not, but it is weird that every single other item works except for the crushed ores.

<img width="855" alt="Screenshot 2023-01-26 at 9 20 35 PM" src="https://user-images.githubusercontent.com/53417820/214996513-b48f60c1-9ac6-48af-a5ef-e735fd1e884c.png">

### Steps to reproduce

1. Create a resource pack using the textures provided on the EEV2 Wiki
2. Apply resource pack to Minecraft
3. Textures should apply to all added EEV2 ores, items, and blocks
4. Crushed Ore textures appear as the black and magenta placeholder blocks instead of the intended crushed ore textures

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.3

### Emendatus Enigmatica version

2.1.x (Latest)

**Comment by Ridanisaurus** [comment]
I noticed that I have stuff textures named incorrectly, and will update them at some point soon.
The texture for the Crushed Ores should be `material_crushed`.
Could you please update the texture name, and verify if it's now working.

**Comment by EnbyChu** [comment]
That namespace worked! Thank you so much!

<img width="856" alt="Screenshot 2023-01-27 at 12 07 35 PM" src="https://user-images.githubusercontent.com/53417820/215149805-f9f6dc52-81a5-497c-a92d-74e35b3ff8a5.png">
