### ISSUE TITLE
Material JSON no longer generates Mekanism or Create ore processing materials

### ISSUE THREAD

**Issue by EnbyChu** [Ridanisaurus/EmendatusEnigmatica#183]
### Issue description

In much of my testing, I has no issue generating the Mekanism and Create ore processing materials. However, in editing the Material files trying to add tools to several of my ores, the in-game generated materials started to do some very odd things.

1. The color module started to function when it previously didn't, applying a tint to all of the item textures. (I then removed the module, as I am already using a resource pack that works).
2. Even though I set the material type to `"metal"`, the mod was generating Clusters and Cluster Shards (which had proper textures through the color module, thankfully). Removing the Cluster material type does not seem to get the mod to generate the ore processing materials.
3. All Mekanism and Create ore processing items had disappeared, in spite of both mods being set to `"true"` in the compat module.
4. The values in the tool module are either being improperly applied, or I do not understand how to set the values correctly in the module, which either way results in the material tools having odd values.
5. The armor module seems to only apply the correct armor value and not the correct toughness, knockback resistance, or set bonus/set description.

I did notice that the example Materials file on the EEV2 wiki is missing a close curly bracket, and it seems to be right after the properties module. When I created my original materials files, I just added a curly bracket to the end to make a JSON checker read it as valid, and that seemed to correctly generate the ore processing items and not the crystal clusters. My current files have curly brackets to close off each module, including adding a bracket to after the properties module; perhaps that is the cause? I'm just not sure how to fix my files in order to get them to work, as I am following the wiki to the best of my understanding. It almost seems like closing that curly bracket fixed the modules _after_ properties in the JSON and broke the properties module in the process.

This file, [platinum.txt](https://github.com/Ridanisaurus/EmendatusEnigmatica/files/10526053/platinum.txt), is the JSON for one of my materials (github wouldn't let me upload it as a .json file).

Both of the below images show the various values being applied oddly to armor and tools, and on the side you can see that the Platinum cluster items are being generated (this was after I removed the color module so they are untextured) and not any of the Mekanism items or Create crushed ores (Create does actually generate its own Crushed Platinum Ore for some reason). 

<img width="858" alt="Screenshot 2023-01-28 at 12 45 38 AM" src="https://user-images.githubusercontent.com/53417820/215248955-175ada1f-6032-4c55-927f-da9ce70ce086.png">

<img width="856" alt="Screenshot 2023-01-28 at 12 47 22 AM" src="https://user-images.githubusercontent.com/53417820/215248958-bbb212a0-60ef-4383-ae74-e8d893c51b1e.png">

I am unsure if this problem is something incorrect on my end, or some quirk on the mod's end like my previous issue with crushed ore textures. 

### Steps to reproduce

1. Add the tools and armor modules to the materials file, and close the curly bracket after the properties module.
2. Open the game and check values for tools/armor and JEI/Creative menu for ore processing items.
3. Values are applied improperly to tools/armor and Mekanism/Create ore processing materials are absent; color module is applied when curly bracket is closed after the properties module.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.3

### Emendatus Enigmatica version

2.1.x (Latest)

**Comment by EnbyChu** [comment]
Tried testing by reverting to an older version of a materials file that did function properly, only for it to no longer function properly and show the above issues. I have no idea what I did to make it work in the first place now.

**Comment by Ridanisaurus** [comment]
> The color module started to function when it previously didn't, applying a tint to all of the item textures. (I then removed the module, as I am already using a resource pack that works).

I did some code refactoring on that module which might explain this. 

> Even though I set the material type to "metal", the mod was generating Clusters and Cluster Shards (which had proper textures through the color module, thankfully). Removing the Cluster material type does not seem to get the mod to generate the ore processing materials.

Could you please elaborate on this. I'm not sure of what seems to be the issue.

> All Mekanism and Create ore processing items had disappeared, in spite of both mods being set to "true" in the compat module.

Do you also have the Mekanism and Create EE Addons in your modpack?

> The values in the tool module are either being improperly applied, or I do not understand how to set the values correctly in the module, which either way results in the material tools having odd values.

> The armor module seems to only apply the correct armor value and not the correct toughness, knockback resistance, or set bonus/set description.

Looking at your Platinum Material, I see you are using `"` on integers, floats, and booleans. You only need to use `"` when it's a string.

**Comment by EnbyChu** [comment]
> Do you also have the Mekanism and Create EE Addons in your modpack?

I do not, it seemed to work before without them but i will definitely add them and try it again.

> Looking at your Platinum Material, I see you are using " on integers, floats, and booleans. You only need to use " when it's a string.

I was not aware of this! i will try fixing this all. My knowledge of json is kind of spotty, to be honest.

> Could you please elaborate on this. I'm not sure of what seems to be the issue.

So, when i first created my materials, i had clusters as a processed type in my list (which admittedly was an accident on my end). I assumed that because i marked the material as a metal in properties that it would ignore making a cluster and make all the other items instead, and so when the clusters started appearing and not the mekanism/create items, i assumed that the properties module was no longer being read. i'm guessing that that's not the case?

Thank you for the help!

EDIT: Tried everything you said, and I guess i must have downloaded, used, and then accidentally uninstalled the compat mods, because putting them in made everything work as intended! Well, everything except the Set Bonus potion effects, but at this point i'm just glad that the issue was my own lacking JSON knowledge and not anything else.

**Comment by Ridanisaurus** [comment]
> I do not, it seemed to work before without them but i will definitely add them and try it again.

V2 of the mod had the compat integrated as a single mod, but as of V2.1 I've moved all compat code to their own addons to avoid massive redundant code build up which makes it a nightmare to maintain on the long term. So moving forward, any compat I add in the future will be its own addon that needs to be added to the modpack.

> So, when i first created my materials, i had clusters as a processed type in my list (which admittedly was an accident on my end). I assumed that because i marked the material as a metal in properties that it would ignore making a cluster and make all the other items instead, and so when the clusters started appearing and not the mekanism/create items, i assumed that the properties module was no longer being read. i'm guessing that that's not the case?

You are correct. Clusters have no relation to the material type. If you don't want Clusters to generate for a material, you just need to remove that from the Processed Type.

> Well, everything except the Set Bonus potion effects

the `effects` is a list of object, so you just need to add [ ] even if it's a single object.
So in your case it should be something like this: 
`"effects": [ { "effect": "minecraft:fire_resistance", "level": 1, "showParticles": false, "showIcon": true } ],`

As there is no bug, I'll proceed to closing this item. 
Happy coding.
