### ISSUE TITLE
[Mekanism] Infuse Types

### ISSUE THREAD

**Issue by Kanzaji** [Ridanisaurus/EmendatusEnigmatica#186]
### Describe the processed type you'd like

Mekanism adds additional type of the material called "Infuse Type", that is used in Metallurgic Infuser for creation of Alloys. They also have "Compressed Version" of the Infuse Type as an item, made in Enrichment Chamber.
Pretty much the basic recipes would be Conversion Recipe from Dust / Gem / Compressed Version of the Infuse Type, to the infusion Type, and from Dust / Gem to the Compressed Varian in enrichment Chamber 😄

### Additional context

Could be really useful for making custom Alloys with Mekanism, or just adding additional ways of creating Metal Alloys 😄

**Comment by BeansBeefBroccoli** [comment]
I second this idea 👍
