### ISSUE TITLE
Suggestion - More Vanilla Like Item Names 

### ISSUE THREAD

**Issue by TheCowKing-moo** [Ridanisaurus/EmendatusEnigmatica#19]
Silly request but I have noticed that the item names are different to what vanilla and some mods like Mekanism do for their ore names.

eg:
  Vanilla: <item:minecraft:diamond_ore>
  EE: <item:emendatusenigmatica:ore_diamond>
  Mekanism: <item:mekanism:osmium_ore>
  EE: <item:emendatusenigmatica:ore_osmium>

Its not the end of the world but it would make it a lot easier for unifying which typically requires me to split the strings to get their type name (eg osmium) which I then chuck into some string indexed array to get things like the corresponding dust for this ore.

**Comment by Ridanisaurus** [comment]
Hello there,

At this point, I have no plans to change the naming convention as it will require all the items introduced by EE to be modified as all of them following the same logic, i.e. dust_osmium, ore_osmium, ingot_osmium ..etc. If simiar requests are raised in the future, then I would take it into consideration. I'm also in the middle of a complete code refactor so before that's done, I have no plans to change anything internally beside the logic.

For unifications, I would recommend using the Tags as all EE items are 100% Forge Tagged which should allow automatic unification as long as the other mods are actually utilizing the tags (sadly, some of them don't for some odd reason).
I do apologize for the inconvenience, and the late reply.

**Comment by Ridanisaurus** [comment]
Should be included in a future release soon, hopefully.

**Comment by Ridanisaurus** [comment]
Released: EE-1.16.3-1.0.0
