### ISSUE TITLE
My game keeps crashing

### ISSUE THREAD

**Issue by Greg727** [Ridanisaurus/EmendatusEnigmatica#198]
### Issue description

I have your mod installed in my modpack and when I'm trying to start my game it keeps crashing cause it says that "Registry Object not present: emendatusenigmatica:enigmatic_hammer"

crash log: [crash-2023-03-26_16.49.42-client.txt](https://github.com/Ridanisaurus/EmendatusEnigmatica/files/11073049/crash-2023-03-26_16.49.42-client.txt)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.8

### Emendatus Enigmatica version

2.1.x (Latest)

**Comment by Octelly** [comment]
Any updates on this? I just ran into this crash today and was wondering if there's an ETA for an updated version.

**Comment by Octelly** [comment]
The issue seems to already resolved guessing by the tags, but might as well share my crash log too: https://gist.github.com/Octelly/f92a29ab52a7cede4697a70e3c680963

**Comment by Octelly** [comment]
Seems the crash for me stemmed from either Krypton: Reforged or CTM. Although CTM doesn't work with another mod in the pack anyway (Create: Alloyed).

**Comment by Ridanisaurus** [comment]
Fixed with V2.1.5
