### ISSUE TITLE
Any chance for a 1.18 release?

### ISSUE THREAD

**Issue by Octelly** [Ridanisaurus/EmendatusEnigmatica#200]
### Describe the feature you'd like

I would like a version available for MC 1.18.2 Forge.

**Comment by Ridanisaurus** [comment]
Negative, I don't support back-porting mods. Maintaining a single version is stressful enough.

**Comment by Ridanisaurus** [comment]
This might be helpful for you: https://www.curseforge.com/minecraft/customization/ico-material-easy-scripts
