### ISSUE TITLE
Materials can't be used for Anvil Repair

### ISSUE THREAD

**Issue by FooterManDev** [Ridanisaurus/EmendatusEnigmatica#203]
### Issue description

![image](https://github.com/Ridanisaurus/EmendatusEnigmatica/assets/71946346/e8074348-f1c5-4fff-bc75-66c55e88b163)
EE generated Tools and Armor can't be repaired using an Anvil.

### Steps to reproduce

Make a Material with a Tool or Armor.
Give it to yourself with a loss in durability, and try to repair it.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.8

### Emendatus Enigmatica version

2.1.x (Latest)

**Comment by Ridanisaurus** [comment]
I'm unable to replicate this report. Could you please provide me with a copy of your Steel material.

**Comment by FooterManDev** [comment]
https://gist.github.com/FooterMan15/0c18a449c3e323765dd7fa9cdc3e6cd3

**Comment by Ridanisaurus** [comment]
I can't replicate this issue. Will do some more digging this weekend.
could you please provide me with a modlist in whichever modpack you are playing/making.

**Comment by FooterManDev** [comment]
[Fun in the Sky](https://www.curseforge.com/minecraft/modpacks/fun-in-the-sky) is the Modpack. Latest version.
I’d give you a proper modlist but I’m out of town, sorry ☹️

**Comment by Ridanisaurus** [comment]
I've done some extensive testing yesterday and I'm still unable to replicate this incident.
If you can provide any more details, that would be great and we can re-open this item.
