### ISSUE TITLE
Aternos and the Add-ons

### ISSUE THREAD

**Issue by JitterySkywalker567** [Ridanisaurus/EmendatusEnigmatica#204]
### Issue description

I was looking to make a modpack for me and my friends on Aternos when I noticed that some (haven't checked all) of the Add-ons aren't available on they're site is there any reasons why?

Sorry for bothering you guys on your issue page.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.20

### Emendatus Enigmatica version

2.1.x (Latest)

**Comment by Ridanisaurus** [comment]
I have no idea what Aternos is, so I can't really say why some of the addons are not available.
Do note that EE and its addons are uploaded exclusively to Curse Forge at the moment, and any uploads on any other 3rd Party Website is neither endorsed, nor support by me.

**Comment by JitterySkywalker567** [comment]
Aternos is a free server hosting website for Minecraft. Thank you for your time.

**Comment by Ridanisaurus** [comment]
Yea, sadly not much control I have over that. You need to reach out to them. Best of luck
