### ISSUE TITLE
Fortune does not affect ores that drop more than one of its material

### ISSUE THREAD

**Issue by Weedoof** [Ridanisaurus/EmendatusEnigmatica#208]
### Issue description

As the title states, fortune doesn't affect drop count for materials from ores such as lapis lazuli or redstone. This affects any pack running EE, such as Enigmatica 9.

### Steps to reproduce

1. Load a world in version 1.8.1 of Enigmatica 9.
2. Run`/fill @s ~ ~ ~ ~3 ~3 ~3 emendatusenigmatica:lapis_ore` to generate a stack-sized block of lapis lazuli ore.
3. Break any number of lapis ore with an unenchanted pickaxe.
4. Run the above command a second time.
5. Break the same amount of ore with any other pickaxe that is enchanted with Fortune 3. If desired, run `/apoth lootify mythic` and slot in a Gem of the Earth or Endersurge gem to raise the effective fortune level higher, or use a quark tome.
6. The amount of lapis gained from each pickaxe should be about the same, regardless of which pickaxe was used.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.20

### Emendatus Enigmatica version

2.1.x (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

N/A

**Comment by Ridanisaurus** [comment]
Could you please provide the JSON of the material you are trying to mine.

**Comment by Weedoof** [comment]
Sure. Here it is.
```
{
  "id": "lapis",
  "source": "vanilla",
  "localizedName": "Lapis Lazuli",
  "disableDefaultOre": true,
  "processedTypes": [
    "ore",
    "dust",
    "gear"
  ],
  "properties": {
    "materialType": "gem",
    "harvestLevel": 1,
    "blockRecipeType": 9
  },
  "oreDrop": {
    "drop": "minecraft:lapis_lazuli",
    "min": 2,
    "max": 5
  }
}
```

**Comment by andrew000** [comment]
Same
