### ISSUE TITLE
#201 reappeared

### ISSUE THREAD

**Issue by furtabs** [Ridanisaurus/EmendatusEnigmatica#213]
### Issue description

https://crashy.net/9c277630-4f7a-4405-b4a3-c57486e98cd7

### Steps to reproduce

1. Launch game
2. Crash

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.23

### Emendatus Enigmatica version

2.1.x (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://crashy.net/9c277630-4f7a-4405-b4a3-c57486e98cd7

**Comment by Ridanisaurus** [comment]
Duplicate of #202
