### ISSUE TITLE
emendatusenigmatica:dimensional_block

### ISSUE THREAD

**Issue by QueenReaperTV** [Ridanisaurus/EmendatusEnigmatica#220]
### Issue description

Trying to launch my game and I am getting a game chrash with the message: 
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: emendatusenigmatica:dimensional_block

### Steps to reproduce

Opening Curse Forge
Launch Enigmatica 9
Launch game
Game crashes

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.14

### Emendatus Enigmatica version

Current Dev Branch (Manually Compiled)

**Comment by Ridanisaurus** [comment]
Duplicate of #202
