### ISSUE TITLE
Texture Issue With Ore

### ISSUE THREAD

**Issue by aswgxf** [Ridanisaurus/EmendatusEnigmatica#24]
**Mod Version**
1.16.4 - 1.0.2

**Describe the bug/enhancement**
When looking at ores with fabulous graphics enabled, other ore textures behind it are visible.

**To Reproduce - if applicable**
1. Enable fabulous graphics
2. Look at ore

**Expected behavior**
I expect to not see a texture glitch.
![image](https://user-images.githubusercontent.com/14831028/101232836-cd67b280-3679-11eb-9b6c-368db4d05ab6.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/14831028/101232823-b88b1f00-3679-11eb-94dc-2f2c6121b839.png)

**Comment by aswgxf** [comment]
I will note that when I enable Fabulous mode I get the following warning message. I do not know if that is related to this issue or if it is unrelated. 
![image](https://user-images.githubusercontent.com/14831028/101232863-fe47e780-3679-11eb-8ed5-67ec5bc53ccf.png)

**Comment by Ridanisaurus** [comment]
That's ... interesting.
Unfortunately there isn't much I can do about this per se. My current graphic card doesn't support `Fabulous` graphics either (not even sure which ones do, and which ones don't), besides, Fabulous graphics is also still pretty experimental. 
Will do some more digging to understand why using that type of graphics settings turns Translucent blocks into X-Ray machines.
Thanks for letting me know.

**Comment by Ridanisaurus** [comment]
Actually, this seems to be an issue with Unsupported Graphic Cards all together, not related to the Ores Blocks.
Same can be replicated with Ice which uses the same `getTranslucent` RednerType.

![image](https://user-images.githubusercontent.com/64355028/101241349-7f909000-36f5-11eb-8f4b-4e15ea69f826.png)

**Comment by Ridanisaurus** [comment]
This is cursed on so many levels.
![image](https://user-images.githubusercontent.com/64355028/101241492-d6e33000-36f6-11eb-8326-1aa18f33405f.png)
