### ISSUE TITLE
[Feature] Allow JSON Control over Strata Stones, Materials, and Dimension Gen

### ISSUE THREAD

**Issue by mosharky** [Ridanisaurus/EmendatusEnigmatica#25]
**Mod Version**
1.0.2

**Describe the bug/enhancement**
https://www.curseforge.com/minecraft/mc-mods/unearthed-forge

I'd love to see the stones Unearthed adds integrated with the ores Emendatus Enigmatica has. It would honestly add so much to the caving experience.

**Comment by Ridanisaurus** [comment]
There are plans in the fairly near future to expose all this control through JSON to modpack developers. This way they can add their own stones, and ores. Until then, I'm trying to avoid anything manually.

**Comment by Ridanisaurus** [comment]
I'll actually keep this open as a constant reminder to work on that feature :)

**Comment by mosharky** [comment]
> 
> 
> I'll actually keep this open as a constant reminder to work on that feature :)

Thanks! I'm excited for the future of this considering how many world-gen mods there are in 1.16
