### ISSUE TITLE
AE2 recipes for equivalent crystals

### ISSUE THREAD

**Issue by mosharky** [Ridanisaurus/EmendatusEnigmatica#26]
**Mod Version**
1.0.2

**Describe the bug/enhancement**
- Recipes for crystal growth using crystals from this mod alongside AE2 Growth accelerators and crystal seeds
- Fluix crystal recipe, much like the one found in AE2

**Comment by Ridanisaurus** [comment]
This is sadly outside my control. All items added by EE are Forge Tag based. So, unless AE2 machines/recipe are made to accept forge-tag input in their recipes, there isn't much I can compat with. You could however look into using KubeJS for such tasks.
