### ISSUE TITLE
[Feature] Iron rod does not have a valid recipe

### ISSUE THREAD

**Issue by BedrockLegends** [Ridanisaurus/EmendatusEnigmatica#30]
**Mod Version**
Input mod version here 1.16.4-1.0.3

**Describe the bug/enhancement**
Updated the mod to the new alpha and there is no recipe for the rods

**To Reproduce - if applicable**

**Expected behavior**

**Screenshots**

**Additional context**

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Ridanisaurus** [comment]
Taking the idea of basic recipes into consideration at a later date. If I go ahead with that implementation, all Rod, Plates, Dusts, and Gears will have custom recipes.

**Comment by Ridanisaurus** [comment]
Released with 1.16.4-1.0.4
