### ISSUE TITLE
[Feature] Add a feature to generate clusters of stone/mix-of-stones

### ISSUE THREAD

**Issue by Ridanisaurus** [Ridanisaurus/EmendatusEnigmatica#33]
**Mod Version**
1.16.4 - 1.0.5

**Describe the bug/enhancement**
Add config to remove/generate Vanilla stones as needed (Stone, Andesite, Diorite, and Granite)

**Comment by ghost** [comment]
Add normal stone to that too, so we can generate worlds like TerraFirmaCraft.

**Comment by Ridanisaurus** [comment]
With KubeJS adding the ability to manipulate the world generation, this feature can be easily done through these systems. I'm However adding the ability to generate clusters of stone/mix-of-stones as a sphere, or a geode ..etc..
