### ISSUE TITLE
[Feature] Add decimal support for chunk spawn chance

### ISSUE THREAD

**Issue by ghost** [Ridanisaurus/EmendatusEnigmatica#37]
**Mod Version**
1.16.4 - 1.0.5

**Describe the bug/enhancement**
Support for less than 1 vein per chunk, or a chance for a chunk to not have ores, ie.
`["Gold Config".Overworld]
		#Average Ores per Chunk [Range: 0 to 64, Default: 7]
		#Range: 0 ~ 64
		count = 0.5`
Where 1 in 2 chunks would have a gold ore vein. This would allow for large, spread out resource nodes.

**Comment by Ridanisaurus** [comment]
Sadly, the above is not possible as the `DepthAverageConfig` which is used to generate the Ores accepts only INT, and not FLOAT.

**Comment by ghost** [comment]
Oh, I wasn't aware of that, thanks for letting me know.
