### ISSUE TITLE
generation of strata blocks dont always work 

### ISSUE THREAD

**Issue by ColdFang** [Ridanisaurus/EmendatusEnigmatica#46]
**Mod Version**
1.16.4-1.1.4

**Describe the bug/enhancement**
strata gen works partially

**To Reproduce - if applicable**
activate strata for quark
see patches of quark stones with correct and incorrect blocks 
(will test create strata later)

**Expected behavior**
all red jasper strata blocks in the screenshot below 

**Screenshots**
![emendbug](https://user-images.githubusercontent.com/13708113/104854203-b61d1580-5905-11eb-9909-69b95f6f1c54.png)

**Comment by ColdFang** [comment]
Also create:

![em2](https://user-images.githubusercontent.com/13708113/104854548-8b33c100-5907-11eb-81d0-37c1f57c4ae5.png)

**Comment by Ridanisaurus** [comment]
Sadly, this comes down to multiple factors such as whether the mod generating the strata is executing on the correct event, and at the correct priority. This is out of my control out of the box. However, this can be easily controller with other generation mods like Terraforged for example. Even KubeJS now allows the generation of world stones.

This is done with KubeJS 
![image](https://user-images.githubusercontent.com/64355028/104870603-37e26280-5949-11eb-9e9c-2c4fb827bf75.png)
and as you can see, 99% at least of the ores work correctly.

If you don't want to result to that, you could look into disabling the Big Cluster from Quark. The small clusters work out of the box with EE.
