### ISSUE TITLE
[Bug] Charged Certus Quartz Can't Create Fluix Crystal

### ISSUE THREAD

**Issue by Yourname942** [Ridanisaurus/EmendatusEnigmatica#48]
**Mod Version**
appliedenergistics2-8.2.0-beta.3
EmendatusEnigmatica-1.16.4-1.1.5
Minecraft 1.16.4
Forge 35.1.29

**Describe the bug**
Note: In Applied Energistics 2 by dropping 1 charged certus quartz, 1 redstone, and 1 nether quartz into water you create 2 fluix quartz crystals
Bug:
Dropping the charged certus quartz crystal from this mod into water does not work in creating certus quartz. (It produces 0 fluix crystals, and the 3 ingrediants do not get removed on producing the fluix crystals)

**To Reproduce - if applicable**
1. drop 1 charged certus quartz crystal from this mod into a block of water (ie a 1x1 hole filled with water)
2. drop 1 redstone into the water
3. drop 1 nether quartz into the water

**Expected behavior**
dropping 1 redstone, 1 nether quartz, and 1 charged certus quartz into water should produce 2 fluix quartz crystals, as well as remove the ingredients dropped that were used to create them.

**Additional context**
Using the certus quartz from applied energistics 2 works fine, but not the one from this mod.

**Comment by Ridanisaurus** [comment]
Sadly, this is an issue for AE2 as they have hardcoded the recipe to use the item ID instead of a Forge tag. 
This can be modified using mods such as KubeJS, or Crafttweaker to exchange the input of that specific recipe.
This is not something I can fix from EE without hardcoding which I would like to avoid.

**Comment by Yourname942** [comment]
How would 

> Sadly, this is an issue for AE2 as they have hardcoded the recipe to use the item ID instead of a Forge tag.
> This can be modified using mods such as KubeJS, or Crafttweaker to exchange the input of that specific recipe.
> This is not something I can fix from EE without hardcoding which I would like to avoid.

How can I achieve this in crafttweaker? Thank you.

**Comment by Ridanisaurus** [comment]
I never used Crafteaker myself, but I would assume it follows the same logic as KubeJS, and if so, it should be as simple as either tabbing into recipe type, and then exchanging the input to either use a Forge Tag, or hardcode EE Gems instead. Alternatively, and if you don't want to mess with CT or KubeJS, I think you can just use a vanilla Datapack if it's exposed from AE2 which I'm not 100% sure if it's. You could check with them on Discord.
