### ISSUE TITLE
[Bug] mismatched items with appliedenergistics2-8.2.0

### ISSUE THREAD

**Issue by fracturecomparator** [Ridanisaurus/EmendatusEnigmatica#49]
**Mod Version**
EmendatusEnigmatica-1.16.4-1.1.5
appliedenergistics2-8.2.0 
(Mekanism-1.16.4-10.0.18.445)
**Describe the bug/enhancement**
with the release of applied energistics2-8.2.0 There is a mis matach in naming.  applied energistics has fluix dust, emendatus enigmatica has fluix crystal dust. resulting in the fluix dust from emendatus enigmaticat not being interchangeable with applied energistics recipes. this was working fine with appliedenergistics2-8.1.0.
Also grinding in any grinder not from applied energisitics yields the enigmatica dust (e.g. mekanisms crusher) thus there is no longer a automated way to obtain fluix dust that can be used in applied energistics recipes.

**To Reproduce - if applicable**
Search for fluix in JEI or other recipe mods, and look at recipes that use the fluix dust of applied energistics or the dust of emendatus enigmatica. The emendatus enigmatica fluix dust can no longer be used in applied energistics recipes.

**Expected behavior**
make emendatus enigmatica fluix dust interchangeable with applied energistics fluix dust in recipes

This is the first time I am reporting a bug, let me know if I need to do things differently

**Comment by Ridanisaurus** [comment]
Thanks for the report. Will look into and see what is the optimal solution.
