### ISSUE TITLE
Crash on Startup when deleting things?

### ISSUE THREAD

**Issue by NillerMedDild** [Ridanisaurus/EmendatusEnigmatica#5]
**Mod Version**
`EmendatusEnigmatica-0.1.0-Alpha-MC1.15.2`

**Describe the bug/enhancement**
Crash during startup. Possibly caused by me deleting the empty configs.

**To Reproduce - if applicable**
Steps to reproduce the behavior: (Haven't verified this)
1. Start game
2. Delete configs quickly
3. See error?

**Expected behavior**
No crashing pls.

**Logs**
https://gist.github.com/NillerMedDild/f92fdc2e086d3eac15008d67e7e613e5#file-gistfile1-txt-L2042

**Comment by Ridanisaurus** [comment]
Seems to be resolved with V 0.1.1
