### ISSUE TITLE
[Feature] Add compacted farming blocks 

### ISSUE THREAD

**Issue by BobVarioa** [Ridanisaurus/EmendatusEnigmatica#50]
**Mod Version**
Latest

**Describe the enhancement**
The addition of compacted farming related items (i.e. crate of apples, carrots, potatoes, etc.) similar to Thermal's or Quark's.

**To Reproduce - if applicable**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Logs**
N/A

**Comment by Ridanisaurus** [comment]
This is technically out of scope for EE. Quark which is in almost every modpack covers all the Vanilla crops, while some other mods which add their own crops also have implemented a compacting version like Thermal Cultivation for example. To add this to crops added by every single food mod would be a Ludacris amount of work, and hell to compat. 
A request like this should be raised to the initial mods that are adding crops without adding a way to compact them into 'Barrels of' and 'Basket of' type of block.
