### ISSUE TITLE
[Feature] Cross-mod Ore Crushing integration (Silent's Mechanisms and Create)

### ISSUE THREAD

**Issue by AbacusOperator** [Ridanisaurus/EmendatusEnigmatica#68]
**Mod Version**
1.16.5-1.2.3 (latest)

**Describe the enhancement**
Both Create and Silent's Mechanisms allow crushing ores for purposes of increased output. The convention is following:

**Silent's Mechanisms**
metal ore -> 2 ore chunks + 10% chance of block of base material (cobbled if applicable)
gem ore -> 2 gems + 10% chance of additional gem + 10% chance of block of base material (cobbled if applicable)
coal ore -> 2 coal + 10% chance of block of base material (cobbled if applicable) + 0.1% diamond

**Create**
metal ore -> 1 crushed ore + 30% chance of additional 2 crushed ores + 12.5% chance of block of ore's base material (cobbled if applicable)
gem ore -> 2 gems + 25% chance of additional gems+ 12.5% chance of block of ore's base material (cobbled if applicable)
coal ore -> 2 coal + 25% chance of additional coal+ 12.5% chance of block of ore's base material (cobbled if applicable)

Both Silent's Mechanisms (note, that recipes for some gems and metals crushing are added not by Silent's Mechanisms, but by Silent's Gems and Silent's Gear, as they add corresponding materials) and Create.

I would like to see integration of this into EmendatusEnigmatica with EmendatusEnigmatica's chunks taking place of Silent's chunks and Create's crushed ores. For example, let's consider diorite aluminum ore:

**Silent's Crushing**:
emendatusenigmatica:aluminum_diorite_ore -> 2 * emendatusenigmatica:aluminum_chunk + 10% minecraft:diorite

**Create's Crushing**:
emendatusenigmatica:aluminum_diorite_ore -> 1 * emendatusenigmatica:aluminum_chunk  + 30% 2 * emendatusenigmatica:aluminum_chunk  + 12.5% minecraft:diorite

Note, that in order to implement these recipes, Silent's and Create's recipes have to be removed, as they rely onto Forge tags and will block any recipes with conflicting input.

**Additional request**: Since EmendatusEnigmatica's chunk replaces Create's crushed ores in this proposal, Create's splashing recipes should be also added to metals chunks if it implemented:
Create's splashing: crushed ore -> 10 nuggets + 50% chance of 5 additional nuggets
This proposal's equivalent: chunk (of metal) -> 10 nuggets + 50% chance of 5 additional nuggets
Example: emendatusenigmatica:aluminum_chunk -> 10 * emendatusenigmatica:aluminum_nugget  + 50% 5 * emendatusenigmatica:aluminum_nugget

**Comment by Ridanisaurus** [comment]
While the above does in fact sound cool, this is a more of a niche compat, and it will vary between 1 modpack and another, this is why I would suggest achieving these results with other recipe control mods like CraftTweaker and KubeJS.
Such mods should give you complete control on recipe inputs and outputs + extras.
