### ISSUE TITLE
Certus Quartz Compatibility 

### ISSUE THREAD

**Issue by NillerMedDild** [Ridanisaurus/EmendatusEnigmatica#7]
**Describe the bug/enhancement**
I would like ores for Certus Quartz added if possible :)

Edit: We talked about this briefly on Discord.

**Comment by Ridanisaurus** [comment]
On it.

**Comment by NillerMedDild** [comment]
I just wanted to formalize it, not rush you :D

**Comment by Ridanisaurus** [comment]
I don't know what you mean? This was part of the mod already. It's under undergoing testing :D

**Comment by Ridanisaurus** [comment]
Released with V1.0.0
