### ISSUE TITLE
[Suggestion] Add Mana and Artifice's Vinteum Ore to the mod

### ISSUE THREAD

**Issue by RomanFlour** [Ridanisaurus/EmendatusEnigmatica#71]
**Mod Version**
Input mod version here

**Describe the bug/enhancement**
I feel like adding Vinteum ore would make the Mana and Artifice mod more easily able to be slotted into packs with this mod, or allow the mod to be used alongside this one.

**Comment by Ridanisaurus** [comment]
I'm currently working on exposing that type of control to modpack developers. 
Until then I won't be adding any manual stones, ores, or processed materials to avoid redundant and duplicated work.

The Data-Driven Refactor is not far from complete, and should hopefully be released in the near future.
