### ISSUE TITLE
(Suggestion) Config option to make otherworldly ores smelt into 2 ores of the overworld counterpart kinda like Netherending ores

### ISSUE THREAD

**Issue by ReiDaTecnologia** [Ridanisaurus/EmendatusEnigmatica#72]
**Mod Version**
N/A
**Describe the bug/enhancement**
Title.

**To Reproduce - if applicable**
1. N/A
2. N/A
3. N/A
4. N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
https://ptb.discord.com/channels/195234321836146688/544822403230859283/825732894940332032

**Logs**
N/A

**Comment by Ridanisaurus** [comment]
Already part of the Data-Driven Refactor.
P.S: Next time provide proper ticket, not just a link to a Discord conversation please.
