### ISSUE TITLE
[Feature Request] Fluids for molten/liquified metals and gems

### ISSUE THREAD

**Issue by AbacusOperator** [Ridanisaurus/EmendatusEnigmatica#76]
**Mod Version**
Minecraft 1.16.5
EmendatusEnigmatica (latest)

**Describe the enhancement**
Add molten metals and gems fluids. This will ease implementation of datapack recipes in various modpacks that involve machines that liquify stuff, manipulate liquids, and solidify liquids. This is especially relevant with recent update of Tinker's Construct to 1.16.5. Mods for which this also will be very useful include Cyclic and Create.

**Expected behavior**
Just technically add fluids for crystalline and metallic materials, no native recipes for them are necessary.

**Comment by Ridanisaurus** [comment]
This feature is already planned for the Data-Driven Refactor.
