### ISSUE TITLE
[Feature Request] Crushed chunks (for metallic ores)

### ISSUE THREAD

**Issue by AbacusOperator** [Ridanisaurus/EmendatusEnigmatica#77]
**Mod Version**
Minecraft 1.16.5
EmendatusEnigmatica (Latest version)

**Describe the enhancement**
Add 'crushed chunks' for metals and 'crushed blends' for alloys. This will ease implementation of datapacks or KubeJS/Crafttweaker scripts for crushing recipes in various modpacks that involve crushing machines as step in ore doubling. Mods that use crushing machines most notably include Create, Silent's Mechanism and Immersive Engineering.

**Expected behavior**
- Add 'crushed chunks' for metallic materials with no native recipes for their production.
- Add 'crushed blends' for alloys, that can be crafted from 'crushed chunks' of corresponding metals by shapeless crafting tables recipes with total quantity of items on both sides being preserved. Example: 1 * "crushed silver chunks" + 1 * "crushed gold chunks" = 2 * "crushed electrum blend".
- Every "crushed chunk" or "crushed blend" can be smelted by Vanilla furnace or Vanilla blasting furnace into exactly one corresponding ingot.

**Additional context**
Reduction of my previous excessive [feature request](https://github.com/Ridanisaurus/EmendatusEnigmatica/issues/68).

**Comment by Ridanisaurus** [comment]
This feature is already planned for the Data-Driven Refactor.
