### ISSUE TITLE
[Feature Request] Ore chunk support for the new MythBot Alfheim dimension's ores

### ISSUE THREAD

**Issue by pm065** [Ridanisaurus/EmendatusEnigmatica#81]
Mythic Botany just updated, adding an Alfheim dimension accessible in the far endgame. It contains Gold Ore, which is pretty easy to change with loot tables, but it also contains Elementium and Dragonstone Ore, which of course do not have ore chunks. 
Total support for the dimension and Livingrock would be cool, but the fact that there is no Undergarden compatability makes me think it couldn't be done easily.

![2021-04-30_16 55 27](https://user-images.githubusercontent.com/81559564/116721300-0f9ce200-a9d5-11eb-8f99-a193661e55b4.png)
(I accidentally pressed the panorama key while taking this screenshot :p)

**Comment by Ridanisaurus** [comment]
Unfortunately, at the moment I would need to hardcode such features, which I'm would rather not.
That been said, I am in the process of rewriting the mod where it will allow ore generation in any dimension. This feature has already been developed, and will be included in the new version
I will keep this item open for testing purposes before the initial refactor release.
