### ISSUE TITLE
[Bug] Missing Mana Tags from Arcane Compat

### ISSUE THREAD

**Issue by Ridanisaurus** [Ridanisaurus/EmendatusEnigmatica#85]
**Mod Version**
1.2.5

**Describe the bug/enhancement**
Missing Mana Tags from Arcane Compat
https://github.com/NillerMedDild/Enigmatica6/issues/2401#issuecomment-860270839

**Comment by NielsPilgaard** [comment]
This isn't fixed sadly. The tag should be `mana` for all the Arcane/Mana Gem components :)
![billede](https://user-images.githubusercontent.com/21295394/122002878-97d31d00-cdb2-11eb-9328-558b715680c4.png)
