### ISSUE TITLE
[Feature Request] Support for Yellorite, Benitoite and Anglesite Ores and their derivatives from Extreme Reactors 2

### ISSUE THREAD

**Issue by DarthCaesium** [Ridanisaurus/EmendatusEnigmatica#89]
Do be aware that their ingots and other related items are called Yellorium/Benitoium/Anglium.

**Comment by Ridanisaurus** [comment]
I have no intent to support these as of this moment as they are extremely mod specific, and ER is not part of Enigmatica which is the main modpack this mod is developed for.
However, once Version 2.0 of the mod is released, modpack devs can add the ores/outputs/processed mats they want as it will be data driven.
