### ISSUE TITLE
[BUG] EE is removing the Crushing Recipe of  JAOPCA 

### ISSUE THREAD

**Issue by ffuentesm** [Ridanisaurus/EmendatusEnigmatica#93]
**Mod Version**
EmendatusEnigmatica-1.16.5-1.2.8

**Describe the bug/enhancement**
JAOPCA has crushing recipes fro the create MOD for different ores, Cobalt is an example.

**To Reproduce - if applicable**
1. Install EE, JAOPCA, Create, the latest Tinkers Construct for 1.16.5
2. Try to crush the Cobalt Ore from Tinkers Construct. 
3. Nothing comes out. 
4. You can also check the JEI recipe list.  There you will see that JAOPCA Crushed Cobalt is no longer there.

**Expected behavior**
It should produce Crushed Cobalt Ore

**Screenshots**
![image](https://user-images.githubusercontent.com/44974827/124528275-d2d6d800-ddd5-11eb-9440-8c5bde875394.png)
![image](https://user-images.githubusercontent.com/44974827/124528355-fa2da500-ddd5-11eb-8396-7910d1918c6a.png)
![image](https://user-images.githubusercontent.com/44974827/124528388-10d3fc00-ddd6-11eb-8d69-1f024db8090a.png)

**Additional context**
The washing recipe from JAOPCA still works, as seen in the above image.

**Comment by Ridanisaurus** [comment]
Please note that EE doesn't add, or remove any of these recipes, I only add the appropriate tags to the Crushed Ore items based on Create Tags. 
We have completely replaced JAOPCA with EE in Enigmatica 6, and created our own recipes with KubeJS, and everything is working as expected.
