### ISSUE TITLE
[Enhancement] Improve JEI integration to hide unused strata/materials

### ISSUE THREAD

**Issue by ctrlaltmilk** [Ridanisaurus/EmendatusEnigmatica#94]
I know that this can already be done with tools like CraftTweaker/KubeJS, but hiding potentially hundreds of items sounds a lot easier on the mod side. There are already configs to turn off generation in specific strata, so it makes sense to have config options to not use some ores. If a certain ore/strata has those settings on, it signals that those items would have no use in the modpack and can be hidden from JEI.

**Comment by Ridanisaurus** [comment]
This has already been addressed in EE V2.0 as everything will be Datadriven, so only the items specified by the modpack devs will be registered.
