### ISSUE TITLE
No Ancient Debris / Netherite Scrap dust.

### ISSUE THREAD

**Issue by Random832** [Ridanisaurus/EmendatusEnigmatica#97]
**Mod Version**
1.16.5-1.2.7

**Describe the bug/enhancement**
There is no dust for Ancient Debris [forge:dusts/netherite_scrap] - this causes problems processing ancient debris in the Fluid Sieving Machine from Industrial Foregoing, which relies on matching ore and dust tags [and for some reason the other IF ore processing machines in Enigmatica 6 accept ancient debris instead of rejecting it; at the end of the chain the sieving machine outputs air].

**Comment by Aleksejus1** [comment]
I have also encountered the same issue, once i didn't get anything i thought that perhaps there's a chance of getting dust and a chance of not, but after processing 4 buckets of ancient debris fermented raw meat i got absolutely nothing :/

**Comment by Ridanisaurus** [comment]
This has already been fixed in a future release of Enigmatica 6. EE doesn't add Netherite Dust because it is already added by Mekanism.

**Comment by Random832** [comment]
Mekanism adds *netherite* dust, not *ancient debris / netherite scrap* dust. The only ancient debris related ore processing item added by Mekanism is 'dirty netherite scrap'.
