### ISSUE TITLE
Ores sometimes generated without strata background

### ISSUE THREAD

**Issue by Heyy-ItsCaitlyn** [Ridanisaurus/EmendatusEnigmatica#98]
**Mod Version**
1.16.5-1.2.4

**Describe the bug/enhancement**
Ores are sometimes generated with the correct strata and sometimes with basic stone.

**To Reproduce - if applicable**
1. Generate new world with strata generation enabled
2. Enter into caves where non-stone strata are present
3. Observe various ore generation that does not always match the background strata

**Expected behavior**
Ores should generate consistently with the background strata

**Screenshots**

(Ignore the create zinc, it obviously would not have strata background because it wasn't generated through this mod)

![EE_bug_1](https://user-images.githubusercontent.com/2576463/126090101-09578f04-fc1f-43ec-9ad4-521e7b4388c5.png)
In this image, several ore types are not generated matching the background strata 

![EE_bug_2](https://user-images.githubusercontent.com/2576463/126090209-391bf80c-11af-432a-8a86-dcabf8decfdb.png)
In this image taken within the same large cave, the foreground copper ore has the andesite background and the slightly further away copper does not, although it should.

Although not shown in these screenshots, in the same cave area the issue occurred on Create limestone in addition to Andesite.

**Comment by Ridanisaurus** [comment]
The problem with Ore Generation is that there are multiple elements that are in play here, for example the event firing priority, or the way some of these mods create these caves and underground tunnels. 
For example, on Enigmatica 6, we use Terraforged which controls the Stone Generation underground, and it has yielded the best results so far, while when letting some mods do their own generation, you can get the odd ore here there, like if a mod replaces Vanilla Stone with their own type of rock/stone, but then that event if fired after the ores have generated, and that's where you get these anomalies of Stone Ore on Non-Stone. Or for example if there is any stone behind these ores, it will still count it as a valid stone ore spot for generation.

In the EE v2.0, we have re-written our own feature for ore generation, and it should hopefully help with reducing these issues. Other than than, there isn't much I can do about it unfortunately. We will continue monitoring the situation, and improve anything we can to help with avoid this.
